service: frontend-vuejs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  profile: default # this is my case

plugins:
 - serverless-apigw-binary
 - serverless-offline
 - serverless-webpack

package:
  include:
    - handler.js
    - .nuxt/**

custom:
  apigwBinary:
    types:
      - '*/*'
  # esbuild:
  #   bundle: true
  #   minify: false


functions:
  nuxt:
    handler: handler.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}
