
---
dev:
  django_settings: django_zappa_lambda.settings
  s3_bucket: django-zappa-john-demo
  profile_name: ffm-sandbox
  keep_warm: false
  # manage_roles: false
  # role_name: Zappa-John-Demo
  vpc_config:
    SubnetIds:
      - subnet-014c17506174d9b21
      - subnet-07084f6101e312b4a
      - subnet-01b12669fffe7546d
    SecurityGroupIds:
      - sg-071ba52c5f9595c2e