
---
dev:
  django_settings: django_zappa_lambda.settings
  s3_bucket: django-zappa-lambda-jolo-dev
  aws_profile: default
  vpc_config:
    SubnetIds:
      - subnet-be1493f2
      - subnet-768fca1c
      - subnet-825bebfe
    SecurityGroupIds:
      - sg-2a36c858